site_name: ADAFEST Docs (v0.1.0)
site_url: https://m-zakeri.github.io
repo_url: https://github.com/m-zakeri/ADAFEST
site_description: A data-driven apparatus for estimating software testability
site_author: Morteza Zakeri
copyright: © 2020-2022 ADAFEST project - Reverse engineering laboratory

theme:
  name: material
  palette:
    - scheme: default
      primary: pink
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/library
  features:
    - header.autohide
  extra:
    social:
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/mortazazakeri/


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
          selection:
            members: True

nav:
    - Home: index.md
    - Metrics: metrics.md
    - Benchmarks: benchmarks.md
    - Datasets: datasets.md
    - Modules:
        - Main: modules/main.md
    - Publications: publications.md
    - Related projects: related_projects.md
    - Issue Tracker: 'https://github.com/m-zakeri/ADAFEST/issues'